### ISSUE TITLE
42

### ISSUE THREAD

**Issue by Mac10goesBRRRT** [Merlinity/movies#1]
Bitte den originalen Per Anhalter

**Comment by Merlinity** [comment]
Gibt es ein Remake?

**Comment by Mac10goesBRRRT** [comment]
Ich meine natürlich die Serie
https://de.wikipedia.org/wiki/Per_Anhalter_durch_die_Galaxis_(Fernsehserie)

**Comment by Merlinity** [comment]
Alles klar, wurde vermerkt
